There was an exception
Test Completed
